name: test

on:
  schedule:
    - cron: "0 16 * * *"  # 1800(JST)
  workflow_dispatch:    # 手動実行可能

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
        run: python fetch_fear_greed.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add data/fear_greed.csv
          git commit -m "Update Fear & Greed CSV" || echo "No changes to commit"
          git push
          
